### ISSUE TITLE
Footer is not working

### ISSUE THREAD

**Issue by Milan-rawat** [harikanani/Hari#6]
![Screenshot 2021-07-27 082625](https://user-images.githubusercontent.com/75739793/127088239-4a6e60ea-ad0c-4ac3-b625-f4ae71e6a780.jpg)

Content is floating over the footer.

**Comment by harikanani** [comment]
Hey! @Milan-rawat would you like to work on this issue? So I'll assign it to you

**Comment by Milan-rawat** [comment]
Yes, of course & Thank you for the invitation @harikanani

**Comment by harikanani** [comment]
Thank you for getting interest on this issue.

**Comment by Milan-rawat** [comment]
Your welcome
